### ISSUE TITLE
Ændring af topfoto

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#102]
Topfoto må gerne skifte imellem 4 forskellige fotos.

Disse 4 fotos skal samtidigt være et link til hver deres leg.

1. Hurtig tovtrækning - http://legedatabasen.dk/leg/hurtig-tovtraekning
2. Sten saks papir - http://legedatabasen.dk/leg/sten-saks-papir
3. Ninja - http://legedatabasen.dk/leg/ninja
4. Trække gulerod - http://legedatabasen.dk/leg/traekke-gulerod

Billeder kan downloades her:
https://www.dropbox.com/sh/az612j2h2xea1f3/AADLhaJ2JFiH7_L5x4Yd4WnTa?dl=0

**Comment by Pilen** [comment]
Skal hele billedet være et link, eller skal der være en knap, evt. Noget lidt mere diskret der vises ved når man har cursoren i toppen?

Det jeg måske kan frygte er at folk tænker at når man trykker på topbilledet så føres man til forsiden, især når der står "legedatabasen.dk" hen over det.

**Comment by peterrandorff** [comment]
Jeg har ikke lige den gode idé til hvordan det skulle være ellers. Gør dem bare til et link til legene lige nu, det centrale er bare at top billedet skifter.

**Comment by Pilen** [comment]
Hold da op de er store, jeg laver lige en lidt mindre udgave.
Her er en oplagt mulighed for at bruge #91 til at skallere ned pr. enhed
