### ISSUE TITLE
Rækkefølge af kategorier

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#118]
Hvad skal rækkefølgen af kategorier være?
Dette gælder både rækkefølgen i swiperen, samt den i selectoren.

**Comment by peterrandorff** [comment]
![image](https://cloud.githubusercontent.com/assets/23461795/24732444/4d8a287c-1a71-11e7-8769-4f50a02ab2b1.png)
![image](https://cloud.githubusercontent.com/assets/23461795/24732450/5626ccf6-1a71-11e7-87be-df243ce908e7.png)

**Comment by peterrandorff** [comment]
øverst er swiperen nederst selectoren
