### ISSUE TITLE
Om siden skal se sådan her ud:

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#121]
![ldb om 001](https://cloud.githubusercontent.com/assets/23461795/24751117/a830b230-1ac8-11e7-92ab-38ba57545930.jpeg)

Den skal åbnes som modal når man trykker på den gule ballon, som vises i højre padding på enheder over 1000 pixel.

**Comment by peterrandorff** [comment]
Billedet og teksten findes herunder

![ldb om siden](https://cloud.githubusercontent.com/assets/23461795/24751497/1aee588a-1aca-11e7-8d2d-1bf146b1c4a8.jpg)

[LDB om siden.docx](https://github.com/Pilen/legedatabasen/files/902329/LDB.om.siden.docx)

**Comment by Pilen** [comment]
Hvad er pointen i både at skrive "fx kimsleg, blindebuk eller lyttelege"
og have linjen "Godt eksempel: ”Blindebuk”"
Ville det ikke være mere simpelt med bare én linje med eksempler (gerne som links)?

**Comment by peterrandorff** [comment]
Det har du fuldkommen ret i. Du får lige en revideret tekst idag.

**Comment by peterrandorff** [comment]
Jeg har ændret i teksten sådan at der kun står et enkelt godt eksempel, under hver kategori. Dette eksempel må gerne laves som link.

Flere eksempler ville undergrave konceptet om det gode eksempel på en leg i legekategorien.

[LDB om siden.docx](https://github.com/Pilen/legedatabasen/files/1054001/LDB.om.siden.docx)
