### ISSUE TITLE
Swiper hænger mellem to slides på ios

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#125]

**Comment by Piltoft** [comment]
Det er ikke et problem på ipad, men kun på iphone. Hvad jeg kan læse mig til så skyldes det hvordan slideren initialiseres under JQM

**Comment by Piltoft** [comment]
Har lavet et midlertidigt fix ved at fjerne display:none; på #container

**Comment by Piltoft** [comment]
Nu virker det! der er tilføjet 1ms delay på swiper init

**Comment by Pilen** [comment]
Jeg kunne godt tænke mig at undersøge om det er delayet der gør forskellen, eller om det er kombinationen af at vise `#container` først og kalde `.init` til sidst.
Men det kan vi altid afprøve en anden dag (efter påske).

**Comment by Piltoft** [comment]
Jeg tror jeg har prøvet alle kombinationer og er 95% sikker på at det er delayet der fikser det.
