### ISSUE TITLE
Navbar hopper når scrollbar forsvinder

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#13]
Når man går ind på en leg der er kort nok til at kunne være i vinduet, så forsvinder scollbaren.
Dette får navbaren til at blive bredere så skjoldet hopper.

Kan fikses ved at sørge for at der altid er en div på 100 view height

**Comment by sorenmalling** [comment]
Browser issue som flere kæmper med

**Comment by Pilen** [comment]
Man kan hvad man vil, nu er der et 100% + 1px højt element på siden, så nu forbliver scrollbaren og vi undgår ting der hopper.
