### ISSUE TITLE
Gør kategorivælgerknapperne pænere

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#136]
Det er noget med at lege med CSS for kategorivælgerknapperne på desktopversionen.
Lige nu beskæres de f.eks. lidt skidt på en for lille skærm.

(Efterfølger til issue #96)

**Comment by peterrandorff** [comment]
Duplikat af https://github.com/Pilen/legedatabasen/issues/96#issuecomment-299719126
