### ISSUE TITLE
Legedatabasen fejler på iOS/IPhone

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#138]
Se https://github.com/Pilen/legedatabasen/issues/96#issuecomment-299720976

**Comment by Pilen** [comment]
@Piltoft Har du nogen mulighed for at åbne en debugger eller en javascript consol i browseren hvor problemet sker?

Ellers må jeg prøve at lave noget magi for at logge hvad der sker på en synlig måde

**Comment by Piltoft** [comment]
![img_0553](https://cloud.githubusercontent.com/assets/23454261/25824609/5617edf6-3440-11e7-8907-c9521d56103e.JPG)
Får kun dette i konsollen på iPhone

**Comment by Pilen** [comment]
Hvad hedder browseren præcist inklusiv version?

**Comment by Piltoft** [comment]
Safari til iOS 10.3.1

**Comment by Piltoft** [comment]
Det sker på samtlige browsere på iOS. Tror det hænger sammen med at den ikke kan fjerne ballonen

**Comment by Pilen** [comment]
Hvad siger den nu?

**Comment by Piltoft** [comment]
![img_0554](https://cloud.githubusercontent.com/assets/23454261/25826222/4bd8187e-3446-11e7-8ef7-585395050ff3.JPG)

**Comment by Pilen** [comment]
og en gang til?
remote debugging er feeeedt.

**Comment by Piltoft** [comment]
![img_0555](https://cloud.githubusercontent.com/assets/23454261/25835459/45dbbf96-347f-11e7-9592-830b917569a1.JPG)

**Comment by Pilen** [comment]
Mer!

**Comment by peterrandorff** [comment]
Ved ikke om det hjælper at få den fra mig.

Dette er gjort i google chrome på macbook pro.

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 08 05" src="https://cloud.githubusercontent.com/assets/23461795/25847948/88bae38a-34b8-11e7-95ef-e5d007d857a0.png">

**Comment by peterrandorff** [comment]
har fået instruks fra jens der kommer helt frisk debugging her nu:

Iphone 6
Safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 26 41" src="https://cloud.githubusercontent.com/assets/23461795/25848545/1e27ab90-34bb-11e7-887d-03f21d9b9304.png">

**Comment by peterrandorff** [comment]
Den virker lige nu på chrome på min macbook helt perfekt men der er problemer med safari på macbook.

Macbook pro
Safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 32 06" src="https://cloud.githubusercontent.com/assets/23461795/25848733/e768af90-34bb-11e7-80f8-70bf10675046.png">

**Comment by Pilen** [comment]
Jeg tilføjer mere og mere output så vi langsomt kan finde frem til fejlen, så prøv at give et til.

**Comment by peterrandorff** [comment]
Macbook pro
Safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 40 08" src="https://cloud.githubusercontent.com/assets/23461795/25848964/e885bea8-34bc-11e7-9e54-6652779858bb.png">


Iphone 6
Safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 41 01" src="https://cloud.githubusercontent.com/assets/23461795/25849002/02917f3a-34bd-11e7-8f56-23320da3d468.png">

**Comment by peterrandorff** [comment]
Jeg har her tømt browser data inden jeg opdaterede.

skal jeg bliver ved med at gøre dette?

**Comment by Pilen** [comment]
Det ser ud til at problemet muligvis er i swiperen, prøv igen

**Comment by peterrandorff** [comment]
Iphone 6
safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 55 26" src="https://cloud.githubusercontent.com/assets/23461795/25849501/0c5e9aa0-34bf-11e7-8f3c-41de77ae24ec.png">


Macbook pro
Safari

<img width="1440" alt="skaermbillede 2017-05-09 kl 13 54 48" src="https://cloud.githubusercontent.com/assets/23461795/25849500/0c5dfe10-34bf-11e7-900e-0e2aeac56f64.png">

**Comment by peterrandorff** [comment]
Nu er der også samme fejl på chrome

**Comment by Pilen** [comment]
Hov ja, det var min fejl. prøv igen.

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 06 47" src="https://cloud.githubusercontent.com/assets/23461795/25849905/a0dd940a-34c0-11e7-8795-facc86a81fa9.png">

<img width="1440" alt="skaermbillede 2017-05-09 kl 14 06 30" src="https://cloud.githubusercontent.com/assets/23461795/25849904/a0dcbb66-34c0-11e7-898f-772da6751071.png">

**Comment by peterrandorff** [comment]
samme problem alle steder

**Comment by Pilen** [comment]
What? prøv lige igen, har flushet cachen et par gange igen.

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 12 34" src="https://cloud.githubusercontent.com/assets/23461795/25850148/74b259a0-34c1-11e7-8fad-bf4a81810bb7.png">

<img width="1440" alt="skaermbillede 2017-05-09 kl 14 12 15" src="https://cloud.githubusercontent.com/assets/23461795/25850149/74e8b8ba-34c1-11e7-8b92-fdb5cd71d496.png">

**Comment by peterrandorff** [comment]
Chromer virker fint nu.

**Comment by Pilen** [comment]
Jeg har på fornemmelsen det her ville være meget nemmere hvis jeg havde adgang til en mac, men prøv igen

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 25 15" src="https://cloud.githubusercontent.com/assets/23461795/25850597/32256efe-34c3-11e7-84d7-7a2ced70967a.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 25 03" src="https://cloud.githubusercontent.com/assets/23461795/25850598/3226fc24-34c3-11e7-9444-1a25586309c7.png">

**Comment by Pilen** [comment]
igen

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 40 13" src="https://cloud.githubusercontent.com/assets/23461795/25851235/48568a08-34c5-11e7-8c64-0b75c92a3fb9.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 40 03" src="https://cloud.githubusercontent.com/assets/23461795/25851234/4854d5f0-34c5-11e7-898f-31ca5c929e23.png">

**Comment by Pilen** [comment]
igen.

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 50 20" src="https://cloud.githubusercontent.com/assets/23461795/25851602/b17840c0-34c6-11e7-9d42-9f9387126d79.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 14 50 07" src="https://cloud.githubusercontent.com/assets/23461795/25851603/b1794eac-34c6-11e7-8606-62b1f6c87f3f.png">

**Comment by Pilen** [comment]
`comparison of 5 !== 5 ==> true`
Så 5 er ikke 5?! Det ligner grangiveligt en typefejl.
prøv lige igen

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 07 37" src="https://cloud.githubusercontent.com/assets/23461795/25852282/1cfa5c3c-34c9-11e7-8ab4-11118b4fab6c.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 07 26" src="https://cloud.githubusercontent.com/assets/23461795/25852284/1d29eb64-34c9-11e7-954c-a89d0cfec710.png">

**Comment by Pilen** [comment]
Ja såmænd! I Safari er swiperens `realIndex` er en streng og ikke et tal.
Det er tilsyneladende en fejl i Safari eller Swiper biblioteket, yay!

Det er rettet ved at altid konvertere til et tal.

Prøv at se om det virker nu.

**Comment by peterrandorff** [comment]
hmm

<img width="1440" alt="skaermbillede 2017-05-09 kl 15 20 53" src="https://cloud.githubusercontent.com/assets/23461795/25852825/fb1d0888-34ca-11e7-9813-e7626a9fc517.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 20 13" src="https://cloud.githubusercontent.com/assets/23461795/25852824/faf75692-34ca-11e7-9321-7b2b0aca7ffe.png">

**Comment by Pilen** [comment]
Det var mærkeligt, prøv nu.

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 36 02" src="https://cloud.githubusercontent.com/assets/23461795/25853442/14d3ecc2-34cd-11e7-9e6a-2252e04f9709.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 35 38" src="https://cloud.githubusercontent.com/assets/23461795/25853443/14d650d4-34cd-11e7-98fa-5fa6a278f85e.png">

**Comment by Pilen** [comment]
igen

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 45 28" src="https://cloud.githubusercontent.com/assets/23461795/25853854/67267d22-34ce-11e7-86e1-1647bdecb0b4.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 44 38" src="https://cloud.githubusercontent.com/assets/23461795/25853853/67250ad2-34ce-11e7-919d-f1eb058fe54b.png">

**Comment by Pilen** [comment]
igen

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 58 20" src="https://cloud.githubusercontent.com/assets/23461795/25854418/318f01a0-34d0-11e7-9edb-6ce5129c22ca.png">
<img width="1440" alt="skaermbillede 2017-05-09 kl 15 57 59" src="https://cloud.githubusercontent.com/assets/23461795/25854423/3379227a-34d0-11e7-8499-0a9b3669edf7.png">

**Comment by Pilen** [comment]
Gad vide om Emil får en mail for hver kommentar? I så fald er jeg bange for at Jens og jeg bliver sat på puslinge til næste år.

Kan du ikke prøve igen Peter?

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 16 13 37" src="https://cloud.githubusercontent.com/assets/23461795/25855044/5cd46a2e-34d2-11e7-83e2-37da9904e4f0.png">

<img width="1440" alt="skaermbillede 2017-05-09 kl 16 12 37" src="https://cloud.githubusercontent.com/assets/23461795/25855042/5ba5af32-34d2-11e7-8a82-b232e2ceba53.png">

Tror Emil har slået fra for længst ;)

**Comment by Pilen** [comment]
Ahhh, det er fordi der er en fejl i jQuery query'en! Chrome er simpelthen for flink og lurer godt at når jeg mangler en slutklamme `]` så skulle den nok have været der.

Og her ser vi problemet med ["robustheds principet"/Postels lov](https://en.wikipedia.org/wiki/Robustness_principle) der siger *"Be conservative in what you do, be liberal in what you accept from others"*.
Da Safari ikke er 'liberal' nok til at håndtere fejlen gør Chrome mig lidt en bjørnetjeneste ved at se igennem fejlen istedet for at gøre mig opmærksom på den.

**Comment by peterrandorff** [comment]
BOOM!!

Og så virker det!

**Comment by Pilen** [comment]
Lækkert, så to fejl på Mac/iOS, og nu kan jeg så gå igang med at fjerne de 100 debug print.

**Comment by Piltoft** [comment]
Peter var lidt for hurtig, alt lader til at virke, men swiperen opdaterer ikke resultaterne

**Comment by Pilen** [comment]
NOOOoooo

**Comment by Pilen** [comment]
Sker der noget når man swiper? Eller er den bare statisk, eller hopper den bare tilbage på hvor den kom fra?

**Comment by peterrandorff** [comment]
Den swiper helt normalt som den skal. Den reorganiserer bare ikke legen efter kategorierne

**Comment by Pilen** [comment]
skriver den noget ud når i swiper?

**Comment by peterrandorff** [comment]
Når du siger skriver ud hvad mener du så?

**Comment by Pilen** [comment]
I konsolen, lige som de billeder du uploadede før. Alle de linjer der er skrevet som "debug: bla bla" er tekst jeg spytter ud rundt omkring i koden. På den måde kan jeg manuelt følge med i hvordan koden opfører sig og hvad der bliver kørt i hvilken rækkefølge, og endnu mere, fortæller det også hvad der *ikke* bliver kørt.

Så hvis du åbner siden, og så swiper en gang til siden og tager et screenshot som før, så kan jeg se om koden bliver kørt korrekt når man swiper.

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 23 38 44" src="https://cloud.githubusercontent.com/assets/23461795/25873911/82b5ebb2-3510-11e7-947a-66417f908271.png">

**Comment by peterrandorff** [comment]
<img width="1440" alt="skaermbillede 2017-05-09 kl 23 39 27" src="https://cloud.githubusercontent.com/assets/23461795/25873931/9aa998a4-3510-11e7-82bf-dd51f5715a0d.png">

**Comment by Pilen** [comment]
virker det nu?

**Comment by Piltoft** [comment]
Nej, det er tilsyneladende SwipeChangeEnd der kun sjældent kører

**Comment by peterrandorff** [comment]
Det virker for mig på både Chrome og safari iPhone.

Tror du skal slette cookies Jens.

**Comment by Piltoft** [comment]
Jeg tier stille, det virker tilsyneladende også for mig nu
