### ISSUE TITLE
Nuværende git commit

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#140]
Kunne vi have en url hvor man kan tilgå nuværende commit data.
`git log -1 --format='{short:"%h", long:"%H", author:"%an", date:"%aD", subject:"%s", body:"%b"}'`
På en url som f.eks. `legedatabasen.dk/git.json`

Denne fil skal *også* caches af varnish. På den måde kan jeg lettere sikre mig at det er den korrekte og nyeste version der arbejdes med.

**Comment by sorenmalling** [comment]
Yeah! Det har jeg sat op nu - så det bør d have fra i morgen af

**Comment by sorenmalling** [comment]
Du har det nu
http://legedatabasen.dk/git.json

**Comment by sorenmalling** [comment]
Opdateres hvert minut sammen med seneste commit bliver hevet ned

**Comment by Pilen** [comment]
Fedt!
