### ISSUE TITLE
Host fonte lokalt

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#18]
Istedet for at hente dem fra googles servere kan vi have dem liggende lokalt.
De er den eneste resource (udover google-analytics) som ikke ligger lokalt.

**Comment by sorenmalling** [comment]
Jens eller Peter, find fontene her og så kan vi loade dem ind

https://github.com/google/fonts

**Comment by Piltoft** [comment]
De relevante fonte skulle gerne være uploaded
