### ISSUE TITLE
Esc. på modals går ikke tilbage

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#24]
Hvis man har åbnet en leg og trykker på Escape-knappen, lukkes legen (bootstraps modal) men url'en forbliver den samme. Der skal ske et "back" kald istedet.

**Comment by sorenmalling** [comment]
$('#myModal').on('hide.bs.modal', function (e) {
 // kør den der javascript funktion som laver håndterer "back" ?
})

**Comment by Pilen** [comment]
Ligeledes hvis man trykker uden for modalen.

**Comment by Pilen** [comment]
Løsningen i 2988e6c er ikke helt ideel, da den bryder konceptet om at lukke en modal svarer til at trykke tilbage til forsiden.
Hvis man indsætter back funktionaliteten på eventet bliver det affyret dobbelt når man trykker på browserens tilbage knap.

Jeg lader det være for nu, men det er noget vi skal kigge på til senere.
