### ISSUE TITLE
Individuel opacity på billede og infobar i legene

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#26]
Kan vi opdele legeboksen, så billedet har en opacity på 70% og infobaren har 90% og tekst og ikoner er upåvirket

**Comment by sorenmalling** [comment]
@Piltoft Klart, du kan bare sætte CSS på de ting du gerne vil påvirke

**Comment by Piltoft** [comment]
Jeg ved ikke hvordan jeg kan opdele den uden at lave rod i det.

**Comment by sorenmalling** [comment]
@Piltoft Er det på visningen med mange lege eller når man ser en enkel leg i modal?

**Comment by Piltoft** [comment]
Visningen på mange lege

**Comment by Pilen** [comment]
Det har handlet om at når Jens satte opacity på hele elementet, så bliver infobaren og dens indhold også påvirket.

Man kunne overveje at lave et overlay oven på billedet, under infobaren, som er transperent hvidt. På den måde kan vi også skifte baggrundsfarve hvis vi ønsker uden at skulle ændre andet.

**Comment by sorenmalling** [comment]
Jeg har kort undersøgt det og det kan gøres ved at flytte billedet fra baggrundsbillede og ind i selve boxen

Eksempel

```
<div class="leg">
<img src="/images/lege/7.png" class="leg-box-image">
<p class="navn outlined">Aberne  i træerne</p>
```

og css som det her

```
img.leg-box-image {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    opacity: 0.7;
}
```

Der går noget radius af boxen med det, men det må undersøges. Jeg kan først pushe det i morgen

**Comment by sorenmalling** [comment]
![image](https://cloud.githubusercontent.com/assets/531918/20305768/70a0a2ea-ab37-11e6-8058-09757950ac00.png)
