### ISSUE TITLE
Nogle lege har ingen kategorier

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#28]
Følgende lege har tilsyneladende ingen kategori:
* Kaptajnen siger
* Kædetagfat
* Bold i spand
* Radiokaraoke
* Tøjklemmekampen
* Edderkoppen
* Hund i lænke
* Cowboynavneleg
* Får-ulv-sten
* Hvem har bolden?
* Prinsessen på ærten

Yderligere så sætter backenden deres game_categories til null istedet for den tomme liste.
Det får swiperen til at kaste en fejl.
@sorenmalling, kan du ikke fikse backenden så game_categories altid er en gyldig liste.

@peterrandorff og @Piltoft, er det meningen at de ikke skal have nogen kategori?
De vises stadig under "Alle lege" og ved specifikke søgninger.

**Comment by Piltoft** [comment]
Alle Lege skal have kategori, jeg skal nok rette til

**Comment by sorenmalling** [comment]
@Pilen `game_categories` vil nu være et tomt array `"game_categories": [],` hvis der ikke er nogen.

Data opdateres hver time, klokken **:05

**Comment by Piltoft** [comment]
Så har legene fået kategorier -jeg lukker
