### ISSUE TITLE
Vi mangler et favicon

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#29]
Vi mangler et favicon (ikonet ved siden af titlen i browserens fane).

**Comment by Piltoft** [comment]
Samme ballon som i swiperen, skal den converteres til et andet format?

**Comment by sorenmalling** [comment]
@Piltoft formatet skal være .ico og filen hedde favicon.ico og være kvadradisk (48x48 eller 60x60 er anbefalet)

https://en.wikipedia.org/wiki/Favicon 

Upload filen til "frontend" mappen og så kan den her sag lukkes

**Comment by Piltoft** [comment]
Det har jeg prøvet, men så bliver baggrunden hvid og ikke transperent

**Comment by Piltoft** [comment]
Nu kører den med en 48x48 png

**Comment by sorenmalling** [comment]
Smukt - luk den her sag ved at trykke på "Close and comment" nede i bunden, når det spiller :)
