### ISSUE TITLE
Forbind frontend med backend

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#3]
Hent data ind fra backend istedet for en statisk fil

**Comment by sorenmalling** [comment]
Scriptet generer en statisk fil som kan læses ind - skal den være dynamisk, kan jeg bare bruge samme script med et http kald

**Comment by Pilen** [comment]
Og så har vi bare et cron-job der genererer en ny fil ind i mellem?
Det lyder som en fin løsning indtil videre, ihvertfald så længe vores data er mere eller mindre statisk.

Så skal vi bare lige have sat de rigtige stier op.

**Comment by sorenmalling** [comment]
Præcis. 

Jeg tager det med stier og opsætning sammen med Anders på fredag når vi er på Rys og snakker adgang

**Comment by sorenmalling** [comment]
Gøres når Anders har sat serveren op :-D
