### ISSUE TITLE
Alle locations siger "plæne" kan det passe?

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#35]

**Comment by Pilen** [comment]
Nævn én leg der ikke kan leges på en plæne!...

**Comment by Pilen** [comment]
Derudover mangler jeg stadig at få adgang til feltet "Game Area" som nævnt i #17 
Lige så snart @sorenmalling sender det data med i data.json kan vi opdatere det.

**Comment by Piltoft** [comment]
Bordlege bør ikke sige "plæne"

**Comment by sorenmalling** [comment]
Er jeg ikke assignet, så ser jeg den ikke - men nu er der game area med :-)

**Comment by Pilen** [comment]
Det er rettet, jeg viser lige nu den første at de mulige områder, jeg antager at dette er fint, er det overhovedet nødvendigt at kunne have flere? pyt det gør nok ikke noget i praksis.

Der er dog ca. 15 lege der tilsyneladende ikke kan leges nogen steder...
