### ISSUE TITLE
Swiper - på mobilen

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#37]
På mobilen loader swiperen meget langsomt når man skifter kategori og fryser hele siden når den står og loader.

**Comment by Pilen** [comment]
Der er også nogle gange hvor den fryser ude i et af yder slidesne, og ikke vil vise billederne ved siden af eller skifte længere. 

Virker den overordnet bedre eller dårligere end den gamle, eller skal vi se efter en anden? Vi skifter nok ikke før efter landsmødet.

**Comment by Piltoft** [comment]
Jeg synes den kører bedre end den gamle.

**Comment by peterrandorff** [comment]
Jeg har lige prøvet at vise hvordan det er at den kører på min iphone. Dette er den samme måde jeg har set den køre på to andre iphones også.

https://www.youtube.com/watch?v=sLHuVsdLSHk

**Comment by Pilen** [comment]
Det der sker når man swiper er at swiperen registrerer at man har swipet og når man har swipet færdigt sender den et "jeg har swipet" event.
Det event lytter vi på, med en funktion der så kalder showCategory functionen, der opdaterer søgemaskinen med den nye kategori. Søgemaskinen er sat til at have et delay på 50ms før den gør noget, det er primært til når man taster og man kunne overveje at ignorere det her/sætte det ned når filtre ændres.
Søge masikinen indsnævrer hvilke lege der skal vises, og kalder så funktionen sort_lege der opdaterer alle legene med en score attribut. Så kaldes isotope der arrangerer alle legene ud fra denne attribut.

Min mistanke er at det slet ikke er swiperen der er sløv, men alt det andet som først skal gøres færdigt før man kan gøre andet, og at det især er isotope der er flaskehalsen. I så fald vil det ikke hjælpe at kigge på swiperen eller skifte den ud.

Det ser ud til at være værst på telefonen, muligvis fordi en computer bare er så meget hurtigere at man ikke ligger lige så meget mærke til det.

**Comment by Pilen** [comment]
Nu her har jeg indført noget debugging information i toppen, her kan i se hvordan isotope bruger alt tiden, og resten bliver stort set brugt på de 50ms delay.
Jeg har halveret tiden ved at den ikke reset'er søgningen hele tiden når man swiper.
Men det tager stadig 2-3 sekunder at arrangere alle elementerne.

At gøre noget ved dette er ikke trivielt og kræver enten:
- At vi finder nogle magiske trylleord vi kan kaste efter isotope.
- At vi bruger et alternativ til isotope.
- Vi laver et alternativ selv.

Noget der også afhænger af hvad vi gerne vil kunne i forhold til at arrangere tingene.
Isotope er et ret kraftfuldt værktøj og kan alle mulige ting med at arrangere ting på fancy måder og animere overgangene, se http://isotope.metafizzy.co/layout.html 
Men hvis vi kun holder os til at alle lege vises i ens firkanter arrangeret i orden fra venstre mod højre, oppefra og ned, så kan vi måske nøjes med noget simplere, især hvis vi også kan undvære animationer.
