### ISSUE TITLE
Billeder

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#38]
Billederne i (thumpnailsne?) altså de enkelte små visninger af legene, skal rykkes op sådan at de centreres omkring midten og ikke toppen. 

Lige nu er toppen af billedet det samme som toppen af visningen.

**Comment by sorenmalling** [comment]
#32

**Comment by sorenmalling** [comment]
Jeg er overbevist om at det er fikset nu ellers må du gerne smide et eksempel og et skærmbillede
