### ISSUE TITLE
Topbillede i browserversion

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#40]
Se vedhæftelse
![capture](https://cloud.githubusercontent.com/assets/23454261/20312793/13ff49ec-ab55-11e6-8fe9-63695b478de0.JPG)

**Comment by Pilen** [comment]
Bliver implementeret når menuen bliver færdigt som nævnt i issue #42

**Comment by Piltoft** [comment]
Denne har høj prioritet

**Comment by sorenmalling** [comment]
Hvad skal jeg se?

**Comment by sorenmalling** [comment]
Eller, hvorfor blev jeg assignet?

**Comment by Pilen** [comment]
@Piltoft, Kan i sende mig billedet?

**Comment by Piltoft** [comment]
Fordi jeg ikke ved hvem kan tager sig af den del og der var ingen assignet til den, så smed jer begge på

**Comment by Piltoft** [comment]
![traekke-gulerod-5717](https://cloud.githubusercontent.com/assets/23454261/20396780/a010c792-ace7-11e6-9cdb-0db525f0643e.jpg)

**Comment by Pilen** [comment]
Hvordan skal det fungere når man scroller ned på siden?
Menuen scroller jo med ned ad siden, skal billedet også bevæge sig med?

Eller skal browser menuen opføre sig anderledes?

**Comment by Piltoft** [comment]
Billedet skal forsvinde, men menuen skal "sticke"

**Comment by Pilen** [comment]
Vi har noget kørende nu. Jeg skal nok få opdateret billedet

**Comment by sorenmalling** [comment]
~~@pilen Jeg har lavet en branch med en ny sticky header som bruger twitter bootstrap elementerne, for at kunne håndtere placeringer mv.~~

https://github.com/Pilen/legedatabasen/commit/98baf916d03f1a4d08c7a8890ac481714463177c

~~Vil du ikke prøve at implementere søgefeltet igen? Evt. bruge min css på det oprindelige for placeringer. Jeg har ingen held med at få søgefunktionen frem igen~~

**Comment by sorenmalling** [comment]
Nevermind, vi kan nu se topbilledet :-) så ignorer sidste besked

**Comment by Pilen** [comment]
Ahh, havde glemt at uploade nogle filer.. hehe ups.

Jeg havde med vilje prøvet at undgå bootstrap lidt, da jeg synes tingene hurtigt bliver lige så besværligt som ikke at bruge det, især hvis man gerne vil have tingene lidt anderledes end bootstrap ønsker.

På et tidspunkt kan vi måske droppe bootstrap helt som afhængighed, det burde også barbere lidt af siden af.

**Comment by Pilen** [comment]
Fungerer det som ønsket?
Kan vi lukke issuet?

**Comment by Piltoft** [comment]
Jatak
