### ISSUE TITLE
Kan modalen hente et billede i højere opløsning?

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#48]
Evt. i "720 x ??" eller bliver den for tung - det er meget grynet

**Comment by sorenmalling** [comment]
Sagtens du siger bare til og så ændrer jeg formaterne. Prøv dig evt. frem med

http://images.contentful.com/ehoqvzhuqkke/4wHO2xFxr2E2AA04AokUI6/d8fe152209271daa93ddf75f7321f30b/10_sekunder.JPG?w=800

og parametrerne her 

https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping

**Comment by Piltoft** [comment]
w=720&h=405&fit=fill&f=faces

**Comment by sorenmalling** [comment]
Done, committet og jobbet er kørt
