### ISSUE TITLE
Fjern kategorien "Alle lege" fra "Håndpistol"

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#49]
Vi tilføjer automatisk kategorien "Alle lege", så den skal ikke tildeles i contentful.
Det er derfor den ikke har noget billede fordi Alle lege kommer først.

**Comment by Piltoft** [comment]
done

**Comment by Pilen** [comment]
Hmm, filtrerede lige legene så alle kategorier indeholdende teksten "alle lege" ignoreres.
Så fejler siden ikke fremover
