### ISSUE TITLE
Vis billeder/thumbnails

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#5]
Vis korrekte billeder (thumbnails) til alle lege.
Der skal være et default billede til lege der ikke har et billede.

**Comment by sorenmalling** [comment]
Billederne skal hentes ned fra contenful

**Comment by sorenmalling** [comment]
Der er både "images" og "videos" nu. Træk billeder ind med en mindre størrelse ved at angive dimensioner

https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping/specify-width-height/retrieve-an-image

**Comment by sorenmalling** [comment]
@Pilen @Piltoft kan vi identificere hvilke størrelser af billederne vi skal bruge, så laver jeg et nyt script som trækker dem ned, så skal vi ikke hente dem fra contentful hver gang og vi kan cache dem.

Er der nogle faste størrelser som vi ved skal bruges?
