### ISSUE TITLE
Den blå og gule bar skal rykkes under billedet og gøres minde

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#50]
![img_0178](https://cloud.githubusercontent.com/assets/23454261/20398354/66d13cfe-aced-11e6-9228-d0415d912b5d.PNG)

**Comment by sorenmalling** [comment]
Men kun på mobiltelefoner? 
Alternativt, skal billedet gøres højere?

**Comment by Piltoft** [comment]
Den skal rykkes under på alle enheder, da 16:9 som billederne er nu også vil passe med de film vi kommer til at ligge op

**Comment by sorenmalling** [comment]
Sådan her ?
![image](https://cloud.githubusercontent.com/assets/531918/20398781/06237c3a-acef-11e6-8686-460fc4caea22.png)
![image](https://cloud.githubusercontent.com/assets/531918/20398810/22fdd7ce-acef-11e6-8d54-a580130784f4.png)

**Comment by Piltoft** [comment]
Det er ihvertfald bedre, så kan Peter fintune efterfølgende. - så skal den blå og gule gøre lavere på mobilen, så de tilsammen er 1,5x topbaren
