### ISSUE TITLE
Man kan ikke lukke modal

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#54]

**Comment by sorenmalling** [comment]
Jeg kan godt lukke modalen, så der må være noget helt specielt du gør og under nogen bestemte forudsætninger. Jeg kan ikke lave noget på det her projekt i dag så vil tidligst kunne se på det i aften i Nyborg

**Comment by Piltoft** [comment]
Helt ok, men jeg kan hverken lukke den på mobilen eller desktop på **knapperne**, men det virker, hvis jeg trykker ved siden af

**Comment by sorenmalling** [comment]
Aktiver det her værktøj

https://developers.google.com/web/tools/chrome-devtools/

og skift til "Console"/"Konsol" fanebladet og genindlæs siden. Åben en leg og forsøg at lukke den. Hvis der kommer nogen røder tekster frem, så sæt dem ind her.

Jeg kan ikke fremprovokere fejlen, så ved ikke hvad jeg skal lede efter

**Comment by Piltoft** [comment]
Der kommer ingen røde tekster, men det er som om at den at den genindlæser legedatabasen når jeg trykker på en leg - det er kommet med @Pilen 's nye isotop-alternativ

**Comment by Piltoft** [comment]
@Pilen - Det er din alfabetiske sortering der bugger - jeg tror den overwriter alle andre sorteringer og derfor også søgningen

**Comment by Pilen** [comment]
Det burde være fikset nu.
Des som skete var at den måde vi arrangere legene på istedet for isotope, er at vi river alle noderne ud af dom'en, altså tager det virtuelle html element ud af siden, sorterer dem og indsætter dem igen.

Men det ser ud til at når man fjerner et element fra dom'en så fjernes alle dets event handlers, det vil sige at at den funktionalitet vi har bundet op på at håndtere et tryk fjernes.
Det vil sige at så virker linket som et helt almindeligt link, hvilket gør at hele siden genindlæses for så at vise legen.

Nu laver vi elementerne til links _efter_ de er blevet rykket rundt.

@Piltoft kan du bekræfte at det virker korrekt nu?

**Comment by Pilen** [comment]
Man kan også bruge "delegated" events, snedigt...
