### ISSUE TITLE
Lege info i oversigt

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#6]
Vis den korrekte lege info i oversigten.

**Comment by sorenmalling** [comment]
Den ser udelukkende ud til at fejle pga. en forkert sti til "marked" JS bibliotek og derfor fejler renderingen. Den returnere også 404 når den prøver at loade marked fra bower_components.

**Comment by Pilen** [comment]
Jeg tror primært det der mentes her var ikonerne i oversigten, og ikke selve beskrivelsen.
Det du mente var nok #21 
Dette er lavet, selvom Peter garanteret vil have det hele ændret!
