### ISSUE TITLE
Søgning på alders navne (pusling osv.)

### ISSUE THREAD

**Issue by Piltoft** [Pilen/legedatabasen#61]
Jeg fik her i weekenden en del spørgsmål på om det var muligt at søge på pusling eller tumling så den blev aldersinddelt. Jeg vil derfor spørge ind til om vi kan lave dette som en mulig søgning?
 
Jeg skal derudover her i næste weekend vise legedatabasen frem til KFUM spejderne og tænkte i den forbindelse også at inkludere deres alders trin så søgningen passer sammen der.

En fuld liste kan ses herunder. 

![image](https://cloud.githubusercontent.com/assets/23454261/20483942/261e02cc-aff5-11e6-9fe5-dc67c1e0ba2a.png)

**Comment by Piltoft** [comment]
Kan iøvrigt se at jeg er logget ind som Jens.

Det er Peter der skriver her :)

**Comment by peterrandorff** [comment]
Har her til aften haft en samtale med Malling omkring om dette overhovedet er en god idé.
Gør vi søgefunktionen dårligere ved at inkluderer dette?

**Comment by Pilen** [comment]
Nej, nej det kan vi sagtens. Den simpleste måde at gøre det på er at oprette et "virtuelt" felt på hver leg, altså at frontenden kigger på hvilken aldersklasse legen matcher og så tilføjer en tekst med alle de passende klasser. Så tilføjer vi dette felt til søgemaskinen. Hvis ens søgning så indeholder ordet puslinge vil alle lege der matcher det ord, hvilket alle 2+ lege gør,  lægge sig i toppen

**Comment by Pilen** [comment]
Den smarte måde er at bruge søgemaskinens filter funktionalitet. 

Søgemaskinen virker ved at den først kører alle de filtre på alle legene for at finde ud af hvilke der skal vises. Så kigger den på de valgte lege og udregner hvor godt de matcher på søge teksten. Lige nu er der defineret 4 simple filtre som knapperne i menuen indstiller. Men jeg har overvejet om vi skulle lave et ekstra "søge filter" som istedet for at tage værdien fra en af knapperne, tager hele søgeteksten istedet. Og så kigger den og ser om der er nogle specifikke ord eller sætninger som den så bruger til at filtrere legene. 

På den måde er det faktisk ret simpelt at få den til at begrænse sig til en af grupperne.
