### ISSUE TITLE
problemer på en lenovo tablet

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#65]
en bruger har sendt mig dette billede som sker på hans Lenovo CE0700 tablet. (Android)

![screenshot_2016-11-22-14-03-00](https://cloud.githubusercontent.com/assets/23461795/20524745/3e16de40-b0bc-11e6-9471-a7a368435de3.png)

**Comment by peterrandorff** [comment]
det er en Lenovo CE0700

**Comment by Pilen** [comment]
Øhmm... Så sagde vi at det var en feature for så trykker man bare og håber på at man får en god leg?

Det ser ud til at problemet er ældre versioner af den indbyggede standard browser på android.
Hvis man bruger chrome, er det ikke et problem, og på min kærestes Samsung Galaxy S5 viser standard browseren det korrekt selv om den tager meget lang tid at indlæse.

Men på min egen telefon får jeg noget der ligner det viste, har bare ikke afprøvet med andet end chrome før nu.


Det handler om at ældre versioner af standard browseren ikke understøtter alle dele af CSS, og vi bruger åbenbart nogle nyere ting end hvad de gamle browsere forstår.
Crap...

Jeg troede ellers at vi havde holdt os fra de nyeste dele af CSS. 

Et bud er at det handler om at `calc` featuren i CSS først bliver understøttet i android 4.4, og at den der ikke understøtter gange og division. Dette bruger vi en del til at udregne størrelsen på lege i oversigten. Når dette fejler ender det så som vist.


Vi kan muligvis lave en fallback løsning, hvor vi først angiver en width uden brug af calc som bare bruger hele bredden, og under denne angiver vi så en width udregnet som nu.
http://stackoverflow.com/a/18570313

**Comment by Piltoft** [comment]
Vi havde også problemet på en ipad 4 på landsmødet. Malling snakkede noget om at den henter nogle dele i forkert rækkefølge

**Comment by peterrandorff** [comment]
Jeg kunne forestille mig at vi indimellem kommer til at have med disse personer som ikke helt kender til brugen af forskellige typer browsere på tablet mv. så jeg tror det er bedst at vi stiler efter en løsning så legedatabasen virker også på disse enheder.

**Comment by Pilen** [comment]
Jeg tror desvære du har ret.

**Comment by Pilen** [comment]
Ok, nu falder den tilbage på at alle lege vises som et 300 * 136.042 px billede hvis ikke udregningen af de rigtige størrelser virker korrekt. Det er ikke det kønneste i og med at der så kommer noget ekstra hvid margen ude til højre, men det virker.

Tilgengæld går det stadig meget langsomt med at få hentet alle legene ind og vist dem

**Comment by Pilen** [comment]
Skal vi håbe på at det bliver løst via #63 og #64
