### ISSUE TITLE
Vis en leg når du skriver den direkte url i adressebaren

### ISSUE THREAD

**Issue by sorenmalling** [Pilen/legedatabasen#9]
Den fejler lige nu med HTTP 404

**Comment by sorenmalling** [comment]
https://github.com/camme/jquery-router-plugin

**Comment by Pilen** [comment]
Hvad er der nu galt med min router funktion :P 
Andet end at alle stier skulle rettes til at være absolute.

Der er måske noget i at vi godt kunne gøre indlæsning af data dovent i baggrunden frem for at skulle hente billederne til alle lege og kategorier først.
Men det tager vi senere

**Comment by sorenmalling** [comment]
Det spiller lækkert :-)

http://dev.legedatabasen.dk/leg/afrikansk-bombebold

**Comment by gaardee** [comment]
Hej drenge

Jeg har slet ikke haft tid til at følge med i udviklingen, og det har ikke
hjulpet at jeg lige har ligget syg i næsten en uge :s

Men jeg kom lige til at kigge på det her, (da jeg jo har fulgt lidt med,
det er jo svært når man får 20 mails i timen ;) ) når jeg åbner legen med
linket, så virker Close knappen ikke.

Desuden så er der en underlig lege titel i bunden, er det meningen? og så
er det ærgerligt at 20 min er delt på to linjer.
[image: Billede indsat i tekst 1]
Men keep up the good work. Det ser super sprødt ud :)

Hilsen Emil

2016-11-17 13:47 GMT+01:00 Søren Malling notifications@github.com:
