### ISSUE TITLE
Legekategori visning på legeopslaget

### ISSUE THREAD

**Issue by peterrandorff** [Pilen/legedatabasen#94]
På er legeopslag skal man udover at kunne se beskrivelsen og noter også kunne se hvilke kategorier legen tilhører.

Det tænker jeg skal gøres så der nederst lægges billeder ind af de kategorier legen tilhører.

**Comment by peterrandorff** [comment]
![image](https://cloud.githubusercontent.com/assets/23461795/24292494/dcc764e8-108d-11e7-9583-d4518147c8d1.png)

**Comment by peterrandorff** [comment]
@Pilen 
Jeg har lavet en grafisk visning af hvordan et legeopslag skal se ud. 
Nyt der her er inkluderet:

1. "Legekategorier" for den enkelte leg. 
Disse skal man kunne trykke på så man kommer ud i en søgning i denne kategori.

2.  "Lege der minder om"
Disse skal som udgangspunkt være lege i samme legekategori(er) som denne leg, hvis ikke dette er muligt skal det være de mest sete lege på legedatabasen.

**Comment by Pilen** [comment]
Legekategorier lavet
