### ISSUE TITLE
Erstat swiper på desktop

### ISSUE THREAD

**Issue by Pilen** [Pilen/legedatabasen#96]
Med knapper

**Comment by Pilen** [comment]
Se #42

**Comment by Pilen** [comment]
Jeg mangler:

* Sørg for at kategorierne om fordeles pænt på mindre skærme, jeg burde nok bare bruge flexbox.
* Vælg 'alle' fra start.
* Sørg for at der kun vises én af delene, enten swiper eller selector.
* Synkroniser korrekt mellem de to.

**Comment by Piltoft** [comment]
Der er problem på iOS iPhone

**Comment by Piltoft** [comment]
![img_0549](https://cloud.githubusercontent.com/assets/23454261/25782789/7eb6fe36-3351-11e7-936a-c09fa27428cc.PNG)

**Comment by peterrandorff** [comment]
Der er også et problem på min desktop version:

<img width="1440" alt="skaermbillede 2017-05-07 kl 18 32 56" src="https://cloud.githubusercontent.com/assets/23461795/25782934/8730b35c-3353-11e7-9e91-b16c21474c9f.png">

**Comment by Pilen** [comment]
Havde ikke fået flushet varnish cachen så den serverede en ældre (midlertidig) udgave af CSS'en, nu burde det virke igen

**Comment by peterrandorff** [comment]
Er det muligt at du kan lave den sådan her når man kommer ind på siden:

<img width="1440" alt="skaermbillede 2017-05-07 kl 18 53 18" src="https://cloud.githubusercontent.com/assets/23461795/25783076/5a455bd8-3356-11e7-8b7a-3c1c6fb8ec83.png">

Sådan her når man bare har valgt en enkelt leg:

<img width="1440" alt="skaermbillede 2017-05-07 kl 18 54 15" src="https://cloud.githubusercontent.com/assets/23461795/25783091/75725262-3356-11e7-9cba-9ceb354f8d18.png">

Og så kan man evt vælge flere lege samtidigt at søge i?

<img width="1440" alt="skaermbillede 2017-05-07 kl 18 54 59" src="https://cloud.githubusercontent.com/assets/23461795/25783097/8cc7f764-3356-11e7-88e7-66242631628c.png">

Så kan man altid opdatere hele siden ved at trykke på ballonen i topbaren og kommer tilbage til en alle lege søgning.

**Comment by Piltoft** [comment]
![img_0551](https://cloud.githubusercontent.com/assets/23454261/25783327/c2f7ddf0-335a-11e7-89e3-263eb30210bb.PNG)
På iOS iPhone står den bare og loader med ballonen og kommer aldrig videre.

**Comment by Pilen** [comment]
Da de resterende ting omkring kategorivælgeren har fået deres egne issues, og selve funktionaliteten virker, så lukker jeg dette issue for at rydde lidt op
